language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - TYPO3=6.2.*

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - env: TYPO3=dev-master

before_script:
  - composer require typo3/cms:$TYPO3
  - composer install --prefer-dist
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-cover=build/logs/clover.xml

after_script:
  - mkdir -p src/FluidTYPO3/Builder
  - ln -s Classes src/FluidTYPO3/Builder
  - vendor/bin/coveralls
