language: php

sudo: false

env: COVERAGE="YES" TYPO3_VERSION="^8"

php:
  - "7.0"
  - "7.1"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer require "typo3/cms:$TYPO3_VERSION"
  - composer install --prefer-dist

before_script: mkdir -p build/logs

script: if [[ "$COVERAGE" != "NO" ]]; then ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml; else ./vendor/bin/phpunit; fi

after_script:
  - ln -s Classes src
  - if [[ "$COVERAGE" != "NO" ]]; then ./vendor/bin/coveralls; fi
