language: php

sudo: false

php:
  - "7.0"
  - "7.1"

cache:
  directories:
    - $HOME/.composer/cache

install: composer install

before_script: mkdir -p build/logs

script: if [[ "$COVERAGE" != "NO" ]]; then TYPO3_PATH_ROOT=`pwd` ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml; else TYPO3_PATH_ROOT=`pwd` ./vendor/bin/phpunit; fi

after_script:
  - ln -s Classes src
  - if [[ "$COVERAGE" != "NO" ]]; then ./vendor/bin/coveralls; fi
